resolver: lts-8.5
allow-newer: true
flags: {}
packages:
- '.'
- '../lnforum-api'
- '../lnforum-lib'
- '../lnforum-sanitize'
- '../lnforum-types-gen'
- '../haskell-api-helpers'
- '../haskell-api-helpers-shared'
extra-deps:
- break-1.0.2
- html-entities-1.1.4.2
- iconv-0.4.1.3
extra-include-dirs:
- /usr/local/opt/openssl/include
extra-lib-dirs:
- /usr/local/opt/openssl/lib
