flags: {}
packages:
- '.'
- '../lnforum-api'
- '../ln-lib'
- '../lnforum-sanitize'
- '../haskell-lnforum-types'
- '../haskell-api-helpers'
- '../haskell-api-helpers-shared'
extra-deps:
- break-1.0.2
- html-entities-1.1.4.2
resolver: lts-8.5
